trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    echo "Installing Miniconda..."
    wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
  displayName: 'Install Miniconda'

- script: |
    echo "Creating Conda environment..."
    $HOME/miniconda/bin/conda env create -f environment.yml
  displayName: 'Create Conda environment'

- script: |
    echo "Activating Conda environment..."
    source $HOME/miniconda/bin/activate
    conda activate mothernet
    echo "Running tests..."
    ls
    pytest -sv mothernet/tests/
  displayName: 'Run tests'
