name: mothernet
channels:
  - conda-forge
  - defaults
dependencies:

  - gcc_linux-64
  - gxx_linux-64
  - ipykernel
  - ipython
  - joblib
  - jupyter_client
  - matplotlib-base=3.6.3=py311h8597a09_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - pandas
  - packaging
  - parso
  - pip
  - prompt-toolkit
  - psutil
  - python
  - python-dateutil
  - pyzmq
  - scipy
  - seaborn
  - setuptools
  - threadpoolctl
  - typing-extensions
  - wheel
  - pip:
    - about-time==4.2.1
    - async-timeout==4.0.2
    - attrs==23.1.0
    - autograd==1.6.2
    - blinker==1.7.0
    - boto3==1.28.85
    - botocore==1.31.85
    - click==8.1.7
    - cloudpickle==2.2.1
    - cma==3.2.2
    - cmake==3.26.0
    - configspace==0.7.1
    - contextlib2==21.6.0
    - dabl==0.2.4
    - deprecated==1.2.14
    - dill==0.3.7
    - docker==6.1.3
    - einops==0.7.0
    - fastjsonschema==2.16.2
    - filelock==3.9.0
    - flask==3.0.0
    - frozenlist==1.3.3
    - fsspec==2023.10.0
    - future==0.18.3
    - gitdb==4.0.11
    - gitpython==3.1.40
    - google-pasta==0.2.0
    - gpytorch==1.11
    - grapheme==0.6.0
    - greenlet==3.0.1
    - gunicorn==21.2.0
    - imbalanced-learn==0.10.1
    - importlib-metadata==6.8.0
    - iniconfig==2.0.0
    - itsdangerous==2.1.2
    - jaxtyping==0.2.23
    - jinja2==3.1.2
    - jmespath==1.0.1
    - jsonschema==4.17.3
    - liac-arff==2.5.0
    - lightgbm==3.3.5
    - lightning==2.1.1
    - lightning-utilities==0.9.0
    - linear-operator==0.5.2
    - lit==15.0.7
    - mako==1.3.0
    - markdown==3.5.1
    - markupsafe==2.1.2
    - minio==7.1.13
    - mlflow==2.8.0
    - more-itertools==10.1.0
    - mpmath==1.3.0
    - multidict==6.0.4
    - multiprocess==0.70.15
    - nbformat==5.7.3
    - networkx==3.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - openai==0.26.2
    - openml==0.14
    - pathos==0.3.1
    - plotly==5.13.0
    - pluggy==1.3.0
    - pox==0.3.3
    - ppft==1.7.6.7
    - protobuf==4.25.0
    - pyarrow==11.0.0
    - pyjwt==2.8.0
    - pymoo==0.6.0.1
    - pyrsistent==0.19.3
    - pytest==7.4.3
    - pytorch-lightning==2.1.1
    - pyyaml==6.0
    - querystring-parser==1.2.4
    - regex==2022.10.31
    - s3fs==0.4.2
    - s3transfer==0.7.0
    - schema==0.7.5
    - scikit-learn
    - smdebug-rulesconfig==1.0.1
    - smmap==5.0.1
    - snakeviz==2.1.1
    - sortedcontainers==2.4.0
    - sqlalchemy==2.0.23
    - sqlparse==0.4.4
    - sympy==1.11.1
    - syne-tune==0.10.0
    - tabulate==0.9.0
    - tblib==1.7.0
    - tenacity==8.2.1
    - tokenizers==0.13.2
    - torch==2.0.0
    - torchmetrics==1.2.0
    - torchvision==0.15.1
    - tqdm==4.64.1
    - transformers==4.26.0
    - triton==2.0.0
    - typeguard==2.13.3
    - ujson==5.8.0
    - websocket-client==1.6.4
    - werkzeug==3.0.1
    - wrapt==1.16.0
    - xmltodict==0.13.0
    - yarl==1.8.2
    - zipp==3.17.0
