name: tabpfn
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=3.5.0=py37h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py37h7f8727e_0
  - attrs=22.1.0=py37h06a4308_0
  - babel=2.11.0=py37h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.11.1=py37h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - brotlipy=0.7.0=py37h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py37h06a4308_0
  - cffi=1.15.1=py37h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=38.0.4=py37h9ce1e76_0
  - cuda=11.6.1=0
  - cuda-cccl=11.6.55=hf6102b2_0
  - cuda-command-line-tools=11.6.2=0
  - cuda-compiler=11.6.2=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.6.55=h42ad0f4_0
  - cuda-cuobjdump=11.6.124=h2eeebcb_0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.6.124=hecbf4f6_0
  - cuda-driver-dev=11.6.55=0
  - cuda-gdb=12.0.90=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.6.1=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.0.78=0
  - cuda-nsight-compute=12.0.0=0
  - cuda-nvcc=11.6.124=hbba6d2d_0
  - cuda-nvdisasm=12.0.76=0
  - cuda-nvml-dev=11.6.55=haa9ef22_0
  - cuda-nvprof=12.0.90=0
  - cuda-nvprune=11.6.124=he22ec0a_0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.6.124=h249d397_0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=12.0.90=0
  - cuda-runtime=11.8.0=0
  - cuda-samples=11.6.101=h8efea70_0
  - cuda-sanitizer-api=12.0.90=0
  - cuda-toolkit=11.6.1=0
  - cuda-tools=11.6.1=0
  - cuda-visual-tools=11.6.1=0
  - cudatoolkit=11.3.1=ha36c431_9
  - debugpy=1.5.1=py37h295c915_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.4=py37h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - freetype=2.12.1=h4a9f257_0
  - gds-tools=1.5.0.59=0
  - giflib=5.2.1=h5eee18b_1
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - icu=58.2=he6710b0_3
  - idna=3.4=py37h06a4308_0
  - importlib-metadata=4.11.3=py37h06a4308_0
  - importlib_metadata=4.11.3=hd3eb1b0_0
  - importlib_resources=5.2.0=pyhd3eb1b0_1
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.15.2=py37h06a4308_0
  - ipython=7.31.1=py37h06a4308_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.18.1=py37h06a4308_1
  - jinja2=3.1.2=py37h06a4308_0
  - jpeg=9e=h7f8727e_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jsonschema=4.16.0=py37h06a4308_0
  - jupyter_client=7.4.8=py37h06a4308_0
  - jupyter_core=4.11.1=py37h06a4308_0
  - jupyter_server=1.23.4=py37h06a4308_0
  - jupyterlab=3.5.2=py37h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.16.5=py37h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.9.2.110=h5c901ab_0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.7.1.112=ha5ce4c0_0
  - libcufile=1.5.0.59=0
  - libcufile-dev=1.5.0.59=0
  - libcurand=10.3.1.50=0
  - libcurand-dev=10.3.1.50=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.2.124=hbbe9722_0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.6.3.124=h3c42840_0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.6.2.124=hb5906b9_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.5.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.4=h11a3e52_0
  - libwebp-base=1.2.4=h5eee18b_0
  - libxml2=2.9.14=h74e7548_0
  - libxslt=1.1.35=h4e12654_0
  - lxml=4.9.1=py37h1edc446_0
  - lz4-c=1.9.4=h6a678d5_0
  - markupsafe=2.1.1=py37h7f8727e_0
  - matplotlib-inline=0.1.6=py37h06a4308_0
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - nb_conda_kernels=2.3.1=py37h06a4308_0
  - nbclassic=0.4.8=py37h06a4308_0
  - nbclient=0.5.13=py37h06a4308_0
  - nbconvert=6.5.4=py37h06a4308_0
  - nbformat=5.7.0=py37h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.5.6=py37h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - notebook=6.5.2=py37h06a4308_0
  - notebook-shim=0.2.2=py37h06a4308_0
  - nsight-compute=2022.4.0.15=0
  - numpy=1.21.5=py37h6c91a56_3
  - numpy-base=1.21.5=py37ha15fc14_3
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=22.0=py37h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.3.0=py37hace64e9_1
  - pip=22.3.1=py37h06a4308_0
  - pkgutil-resolve-name=1.3.10=py37h06a4308_0
  - prometheus_client=0.14.1=py37h06a4308_0
  - prompt-toolkit=3.0.36=py37h06a4308_0
  - psutil=5.9.0=py37h5eee18b_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyrsistent=0.18.0=py37heee7806_0
  - pysocks=1.7.1=py37_1
  - python=3.7.16=h7a1cb2a_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-fastjsonschema=2.16.2=py37h06a4308_0
  - pytorch=1.12.1=py3.7_cuda11.3_cudnn8.3.2_0
  - pytorch-cuda=11.8=h7e8668a_3
  - pytorch-mutex=1.0=cuda
  - pytz=2022.7=py37h06a4308_0
  - pyzmq=23.2.0=py37h6a678d5_0
  - readline=8.2=h5eee18b_0
  - requests=2.28.1=py37h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=65.6.3=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.2.0=py37h06a4308_1
  - soupsieve=2.3.2.post1=py37h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - terminado=0.17.1=py37h06a4308_0
  - tinycss2=1.2.1=py37h06a4308_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=py37h06a4308_0
  - torchaudio=0.12.1=py37_cu113
  - torchvision=0.13.1=py37_cu113
  - tornado=6.2=py37h5eee18b_0
  - traitlets=5.7.1=py37h06a4308_0
  - typing-extensions=4.4.0=py37h06a4308_0
  - typing_extensions=4.4.0=py37h06a4308_0
  - urllib3=1.26.14=py37h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py37_1
  - websocket-client=0.58.0=py37h06a4308_4
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.10=h5eee18b_1
  - zeromq=4.3.4=h2531618_0
  - zipp=3.11.0=py37h06a4308_0
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - annoy==1.17.1
      - auto-sklearn==0.15.0
      - catboost==1.1.1
      - click==8.1.3
      - cloudpickle==2.2.1
      - configspace==0.4.21
      - cycler==0.11.0
      - cython==0.29.33
      - dask==2022.2.0
      - distributed==2022.2.0
      - distro==1.8.0
      - emcee==3.1.4
      - fonttools==4.38.0
      - fsspec==2023.1.0
      - future==0.18.3
      - gpytorch==1.8.1
      - heapdict==1.0.1
      - hyperopt==0.2.7
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - liac-arff==2.5.0
      - lightgbm==3.3.5
      - locket==1.0.0
      - matplotlib==3.5.3
      - minio==7.1.13
      - msgpack==1.0.4
      - networkx==2.6.3
      - openml==0.13.0
      - pandas==1.3.5
      - partd==1.3.0
      - plotly==5.13.0
      - py4j==0.10.9.7
      - pyarrow==11.0.0
      - pynisher==0.6.4
      - pyparsing==3.0.9
      - pyrfr==0.8.3
      - python-graphviz==0.20.1
      - pyyaml==6.0
      - scikit-learn==0.24.2
      - scipy==1.7.3
      - seaborn==0.11.0
      - smac==1.2
      - sortedcontainers==2.4.0
      - tabpfn==0.1.8
      - tblib==1.7.0
      - tenacity==8.1.0
      - threadpoolctl==3.1.0
      - toolz==0.12.0
      - tqdm==4.64.1
      - xgboost==1.6.2
      - xmltodict==0.13.0
      - zict==2.2.0
prefix: /anaconda/envs/tabpfn
